# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/entropy',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/entropy',
                'lib_path': 'entropy'},
  'syms': {'entropy.core': {'entropy.core.foo': ('core.html#foo', 'entropy/core.py')}}}
